# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - GlobalTickets/GlobalTickets.Services.Marketing/*
    - GlobalTickets/aks-globaltickets.services.marketing.yaml

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '86a9c183-a3b0-48e6-931a-4358122f8d06'
  imageRepository: 'globaltickets.services.marketing'
  containerRegistry: 'globaltickets.azurecr.io'
  dockerfilePath: 'GlobalTickets/GlobalTickets.Services.Marketing/Dockerfile'
  tag: '$(Build.BuildId)'
  deploymentFile: 'aks-globaltickets.services.marketing.yaml'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        buildContext: $(Build.SourcesDirectory)/GlobalTickets
        tags: |
          $(tag)
- stage: Deploy
  displayName: Deploy to k8s
  jobs:  
  - job: Deploy
    displayName: Deploy to k8s
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: replacetokens@3
      inputs:
        rootDirectory: '$(Build.SourcesDirectory)/GlobalTickets'
        targetFiles: '$(deploymentFile)'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        useLegacyPattern: false
        enableTelemetry: true
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'globaltickets-aks'
        namespace: 'default'
        command: 'apply'
        useConfigurationFile: true
        configuration: '$(Build.SourcesDirectory)/GlobalTickets/$(deploymentFile)'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
        azureSubscriptionEndpointForSecrets: 'MVPSponsorship (e57087a4-a053-48c9-8857-995316398cdc)'
        azureContainerRegistry: 'globaltickets.azurecr.io'
        secretName: 'pullkey'
