apiVersion: v1
kind: Service
metadata:
  name: svc-globaltickets-services-payment
  labels:
    version: dev
    product: globaltickets-services-payment
spec:
  selector:
    app: globaltickets-services-payment
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-globaltickets-services-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globaltickets-services-payment
  template:
    metadata:
      labels:
        app: globaltickets-services-payment
    spec:
      containers:
      - name: globaltickets-services-payment
        image: globalticketsacr.azurecr.io/globaltickets.services.payment:1
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: ServiceBusConnectionString
          value: Endpoint=sb://globaltickets.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=Hi0hqUzgNIhGOcceT/gW4B23fHSlbVM+FPAxjq3zZTc=
        - name: subscriptionName
          value: globalticketspayment
        - name: OrderPaymentRequestMessageTopic
          value: orderpaymentrequestmessage
        - name: OrderPaymentUpdatedMessageTopic
          value: orderpaymentupdatedmessage       
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: "0.10"
      imagePullSecrets:
        - name: acr-secret
