apiVersion: v1
kind: Service
metadata:
  name: svc-globaltickets-services-marketing
  labels:
    version: dev
    product: globaltickets-services-marketing
spec:
  selector:
    app: globaltickets-services-marketing
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-globaltickets-services-marketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globaltickets-services-marketing
  template:
    metadata:
      labels:
        app: globaltickets-services-marketing
    spec:
      containers:
      - name: globaltickets-services-marketing
        image: globalticketsacr.azurecr.io/globaltickets.services.marketing:1 
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: ApiConfigs__ShoppingBasket__Uri
          value: http://svc-globaltickets-services-shoppingbasket
        - name: ConnectionStrings__DefaultConnection
          valueFrom: 
            secretKeyRef:
              name: marketing-db
              key: connectionstring
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: "0.10"
      imagePullSecrets:
        - name: acr-secret
