apiVersion: v1
kind: Service
metadata:
  name: svc-globaltickets-gateway-webbff
  labels:
    version: dev
    product: globaltickets-gateway-webbff
spec:
  selector:
    app: globaltickets-gateway-webbff
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-globaltickets-gateway-webbff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globaltickets-gateway-webbff
  template:
    metadata:
      labels:
        app: globaltickets-gateway-webbff
    spec:
      containers:
      - name: globaltickets-gateway-webbff
        image: globalticketsacr.azurecr.io/globaltickets.gateway.webbff:1
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: ApiConfigs__EventCatalog__Uri
          value: http://svc-globaltickets-services-eventcatalog
        - name: ApiConfigs__ShoppingBasket__Uri
          value: http://svc-globaltickets-services-shoppingbasket
        - name: ApiConfigs__Payment__Uri
          value: http://svc-globaltickets-services-payment
        - name: ApiConfigs__Order__Uri
          value: http://svc-globaltickets-services-ordering
        - name: ApiConfigs__Marketing__Uri
          value: http://svc-globaltickets-services-Marketing
        - name: ApiConfigs__Eventcatalog__Uri
          value: http://svc-globaltickets-services-eventcatalog
        - name:  ApiConfigs__Discount__Uri
          value: http://svc-globaltickets-services-discount
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: "0.10"
      imagePullSecrets:
        - name: acr-secret
