version: '3.4'

services:
  globaltickets.web:
    image: ${DOCKER_REGISTRY-}globalticketsweb
    build:
      context: .
      dockerfile: GlobalTickets.Client/Dockerfile
    environment:
      - ApiConfigs__EventCatalog__Uri=http://globaltickets.services.eventcatalog
      - ApiConfigs__ShoppingBasket__Uri=http://globaltickets.services.shoppingbasket

  globaltickets.services.eventcatalog:
    image: ${DOCKER_REGISTRY-}globalticketsserviceseventcatalog
    build:
      context: .
      dockerfile: GlobalTickets.Services.EventCatalog/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=db;Initial Catalog=GlobalTicketsEventCatalogDb;Integrated Security=False;User ID=sa;Password=P(ssw0rd0123);Connect Timeout=60;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;
    depends_on:
      - db

  globaltickets.services.shoppingbasket:
    image: ${DOCKER_REGISTRY-}globalticketsservicesshoppingbasket
    build:
      context: .
      dockerfile: GlobalTickets.Services.ShoppingBasket/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=db;Initial Catalog=GlobalTicketsShoppingBasketDb;Integrated Security=False;User ID=sa;Password=P(ssw0rd0123);Connect Timeout=60;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;
      - ApiConfigs__EventCatalog__Uri=http://globaltickets.services.eventcatalog
    depends_on:
      - db
  
  external.paymentgateway:
    image: ${DOCKER_REGISTRY-}externalpaymentgateway
    build:
      context: .
      dockerfile: External.PaymentGateway/Dockerfile


  globaltickets.web.bff:
    image: ${DOCKER_REGISTRY-}globalticketswebbff
    build:
      context: .
      dockerfile: GlobalTickets.Web.Bff/Dockerfile


  globaltickets.gateway.mobilebff:
    image: ${DOCKER_REGISTRY-}globalticketsgatewaymobilebff
    build:
      context: .
      dockerfile: GlobalTickets.Gateway.MobileBff/Dockerfile


  globaltickets.gateway.webbff:
    image: ${DOCKER_REGISTRY-}globalticketsgatewaywebbff
    build:
      context: .
      dockerfile: GlobalTickets.Gateway.WebBff/Dockerfile


  globaltickets.services.discount:
    image: ${DOCKER_REGISTRY-}globalticketsservicesdiscount
    build:
      context: .
      dockerfile: GlobalTickets.Services.Discount/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=db;Initial Catalog=GlobalTicketsDiscountDB;Integrated Security=False;User ID=sa;Password=P(ssw0rd0123);Connect Timeout=60;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;
    depends_on:
      - db
  


  globaltickets.services.marketing:
    image: ${DOCKER_REGISTRY-}globalticketsservicesmarketing
    build:
      context: .
      dockerfile: GlobalTickets.Services.Marketing/Dockerfile
    environment:
      - ApiConfigs__ShoppingBasket__Uri=http://globaltickets.services.shoppingbasket

  globaltickets.services.ordering:
    image: ${DOCKER_REGISTRY-}globalticketsservicesordering
    build:
      context: .
      dockerfile: GlobalTickets.Services.Order/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=db;Initial Catalog=GlobalTicketsOrderingDB;Integrated Security=False;User ID=sa;Password=P(ssw0rd0123);Connect Timeout=60;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;
      - ServiceBusConnectionString=Endpoint=sb://globaltickets.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=Hi0hqUzgNIhGOcceT/gW4B23fHSlbVM+FPAxjq3zZTc=
      - CheckoutMessageTopic=checkoutmessage
      - OrderPaymentRequestMessageTopic=orderpaymentrequestmessage
      - OrderPaymentUpdatedMessageTopic=orderpaymentupdatedmessage
    depends_on:
      - db

  globaltickets.services.payment:
    image: ${DOCKER_REGISTRY-}globalticketsservicespayment
    build:
      context: .
      dockerfile: GlobalTickets.Services.Payment/Dockerfile
    environment:
      - ServiceBusConnectionString=Endpoint=sb://globaltickets.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=Hi0hqUzgNIhGOcceT/gW4B23fHSlbVM+FPAxjq3zZTc=
      - subscriptionName=globalticketspayment
      - OrderPaymentRequestMessageTopic=orderpaymentrequestmessage
      - OrderPaymentUpdatedMessageTopic=orderpaymentupdatedmessage
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    expose:
     - "1433"
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=P(ssw0rd0123)


